#!/bin/sh -l
#PBS -V
#PBS -q debug
#PBS -l nodes=1:ppn=20
#PBS -l walltime=00:20:00
#PBS -N output_test

cd $PBS_O_WORKDIR
module load devel
module load matlab


./rungen.sh ../../../../control/Denoisers/BLF_4D/master.txt


# cp -r ../../../../binaries/Inversion/object.recon ../../../../binaries/BLF_4D/noisyImage.recon
# cp -r ../../../../binaries/Inversion/object.recon ../../../../binaries/BLF_4D/denoisedImage.recon


############## copy from inversion
# nT=60
# noisyList=$(readlink -f ../../../../control/Denoisers/BLF_4D/noisyBinaryFName_timeList.txt)
# denoisedList=$(readlink -f ../../../../control/Denoisers/BLF_4D/denoisedBinaryFName_timeList.txt)
# echo $nT > $noisyList
# echo $nT > $denoisedList
# for (( t = 0; t < ${nT}; t++ )); do
# 	fileInv=../../../../binaries/Inversion/timeclone_object_T_${t}.recon
# 	fileInv_abs=$(readlink -f ${fileInv})
# 	# echo $fileInv_abs

# 	fileNoisy=../../../../binaries/BLF/noisyImage_T_${t}.recon
# 	fileNoisy_abs=$(readlink -f ${fileNoisy})
# 	echo $fileNoisy_abs >> $noisyList
# 	# echo $fileNoisy_abs

# 	fileDenoised=../../../../binaries/BLF/denoisedImage_T_${t}.recon
# 	fileDenoised_abs=$(readlink -f ${fileDenoised})
# 	echo $fileDenoised_abs >> $denoisedList
# 	# echo $fileDenoised_abs

# 	cp -r $fileInv_abs $fileNoisy_abs
# 	cp -r $fileInv_abs $fileDenoised_abs

# done


./run.sh ../../../../control/Denoisers/BLF_4D/master.txt
# ./run_chunked.sh ../../../../control/Denoisers/BLF_4D/master.txt

echo "##########################################################"
checkjob -v $PBS_JOBID

