#!/bin/bash

rm mbircone/*.c
rm mbircone/*.so
rm -r build
rm -r dist
rm -r mbircone.egg-info

conda env create -n test_mbircone python=3.8 &&

source activate test_mbircone &&

pip install -r requirements.txt &&

pip install -r demo/requirements_demo.txt &&

# pip install . &&

python setup.py install &&

cd demo &&

python demo.py &&

cd ..

conda deactivate
 
conda remove --name test_mbircone --all




# conda env create -n mbircone python=3.8

# source activate mbircone

# pip install -r requirements.txt

# pip install -r demo/requirements_demo.txt

# python setup.py install

# cd demo

# python demo.py
