#!/bin/bash

conda env create -n test_mbircone python=3.8 &&

source activate test_mbircone &&

pip install -r requirements.txt &&

# pip install . &&

python setup.py install &&

cd demo &&

python demo.py &&

cd .. &&

conda deactivate &&
 
conda remove --name test_mbircone --all
