#!/bin/bash

rm mbircone/cone3D/*.c
rm mbircone/cone3D/*.so
rm -r build
rm -r dist
rm -r mbircone.egg-info

conda create -n test_mbircone python=3.8 &&

source activate test_mbircone &&

pip install -r requirements.txt &&

pip install -r demo/requirements_demo.txt &&

pip install . &&
# pip install -e . &&
# python setup.py install &&


cd demo &&

python demo.py &&
# python demo_compare_ref_cython.py &&

cd ..

conda deactivate
 
conda remove --name test_mbircone --all




# conda create -n mbircone python=3.8

# source activate mbircone

# pip install -r requirements.txt

# pip install -r demo/requirements_demo.txt

# pip install .

# cd demo

# python demo.py
