job_queue_system_type: LocalHost # Support SLURM, SGE, and LocalHost
cluster_params:
  num_worker_per_node: 2
  num_nodes: 1
  num_threads_per_worker: 2
  maximum_allowable_walltime:
  maximum_memory_per_node:
  system_specific_args:
  local_directory:
  log_directory:
