#!/bin/sh -l
#PBS -V
#PBS -q bouman
#PBS -l nodes=2:ppn=20
#PBS -l walltime=00:336:00:00
#PBS -N jobrun_multiNode_init
#PBS -e outputs/error_jobrun_multiNode_init.txt
#PBS -o outputs/output_jobrun_multiNode_init.txt

cd $PBS_O_WORKDIR
module load rcac
module load matlab



./multiNode_setup.sh init

echo "$(checkjob -v ${PBS_JOBID})" | mailx -s "Your Job on $(hostname -s) is ready" "$(whoami)@rcac.purdue.edu"

checkjob -v ${PBS_JOBID}

sleep 9999999999



